fix(pgadmin4): correctly handle int and bool values in servers.json
Because Helm feeds raw YAML to the YAML parser before it ever sees any
Go-template syntax, we need to quote the port part. Else it results in:

```
Error: cannot load values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.example.port":interface {}(nil)}
```